name: dotnet package publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore ./Domain.Pkg
      - name: Build
        run: dotnet build ./Domain.Pkg --configuration Release
      - name: Test
        run: dotnet test ./Domain.Test
      - name: Create pkg
        run: dotnet pack Domain.Pkg.csproj -p:PackageVersion=1.0.74
        working-directory: ./Domain.Pkg
      - name: Archive Nuget
        uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: "**/*.nupkg"
      - name: Publish Nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          
      